services:

  # === Internal API Gateway ===
    api-gateway-internal:
      image: api-gateway-internal
      build: ./api-gateway-internal
      ports:
        - "8080:8080"  # Internal gateway
      networks:
        - soa-net

  # # === Prosumers ===
    itinerary-aggregator:
      image: itinerary-aggregator
      build: ./itinerary-aggregator
      depends_on:
        - api-gateway-internal
      networks:
        - soa-net
  
    availability-coordinator:
      image: availability-coordinator
      build: ./availability-coordinator
      depends_on:
        - api-gateway-internal
      networks:
        - soa-net

  ## === Providers ===
  # provider-trails:
  # image: provider-trails
  #  build: ./provider-trails
  #  networks:
  #    - soa-net
  #  ports:
  #    - "8081:8081"

  # provider-weather:
  #   image: provider-weather
  #   build: ./provider-weather
  #   networks:
  #     - soa-net
  #
  # provider-events:
  #   image: provider-events
  #   build: ./provider-events
  #   networks:
  #     - soa-net
  #
  # # Optional provider for local gastronomy
  # provider-food:
  #   image: provider-food
  #   build: ./provider-food
  #   networks:
  #     - soa-net

networks:
  soa-net:
    driver: bridge
