services:

  # === Internal API Gateway ===
  api-gateway-internal:
    env_file:
      - .env
    image: api-gateway-internal
    build:
      context: ./api-gateway-internal
      args:
        API_GATEWAY_INTERNAL_PORT: ${API_GATEWAY_INTERNAL_PORT}
    ports:
      - "${API_GATEWAY_INTERNAL_PORT:-8080}:${API_GATEWAY_INTERNAL_PORT:-8080}" # Internal gateway
    networks:
      - soa-net

  client-gui:
    env_file:
      - .env
    image: client-gui
    build:
      context: ./clientGui/
      args:
        CLIENT_APP_PORT: ${CLIENT_APP_PORT}
    ports:
      - "${CLIENT_APP_PORT}:${CLIENT_APP_PORT}"
    networks:
      - soa-net

  # === Prosumers ===
  trip-planner:
    env_file:
      - .env
    image: trip-planner
    build: 
        context: ./tripPlanner/
        args: 
          TRIP_PLANNER_PORT: ${TRIP_PLANNER_PORT}

    ports:
      - "${TRIP_PLANNER_PORT:-8090}:${TRIP_PLANNER_PORT:-8090}"
    depends_on:
      - api-gateway-internal
    networks:
      - soa-net

  location-availability:
    env_file:
      - .env
    image: location-availability
    build:
      context: ./locationAvailability/
      args:
        AVAILIBALITY_LOCATION_PORT: ${AVAILIBALITY_LOCATION_PORT}
    ports:
      - "${AVAILIBALITY_LOCATION_PORT:-8086}:${AVAILIBALITY_LOCATION_PORT:-8086}"
    depends_on:
      - api-gateway-internal
    networks:
      - soa-net

  # === Providers ===
  provider-trails:
    env_file:
      - .env
    image: provider-trails
    build:
      context: ./provider-trails
      args:
        PROVIDER_TRAILS_PORT: ${PROVIDER_TRAILS_PORT}
    ports:
      - "${PROVIDER_TRAILS_PORT:-8081}:${PROVIDER_TRAILS_PORT:-8081}"
    networks:
      - soa-net

  provider-weather:
    env_file:
      - .env
    image: provider-weather
    build:
      context: ./provider-weather
      args:
        PROVIDER_WEATHER_PORT: ${PROVIDER_WEATHER_PORT}
    ports:
      - "${PROVIDER_WEATHER_PORT:-8082}:${PROVIDER_WEATHER_PORT:-8082}"
    networks:
      - soa-net

  provider-events:
    env_file:
      - .env
    image: provider-events
    build:
      context: ./provider-events
      args:
        PROVIDER_EVENTS_PORT: ${PROVIDER_EVENTS_PORT}
    ports:
      - "${PROVIDER_EVENTS_PORT:-8084}:${PROVIDER_EVENTS_PORT:-8084}"
    networks:
      - soa-net

  provider-food:
    env_file:
      - .env
    image: provider-food
    build:
      context: ./provider-food
      args:
        PROVIDER_FOOD_PORT: ${PROVIDER_FOOD_PORT}
    ports:
      - "${PROVIDER_FOOD_PORT:-8083}:${PROVIDER_FOOD_PORT:-8083}"
    networks:
      - soa-net
    environment:
      SPRING_PROFILES_ACTIVE: default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PROVIDER_FOOD_PORT:-8083}/food-api/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  soa-net:
    driver: bridge
