services:

  # === Internal API Gateway ===
  api-gateway-internal:
    image: api-gateway-internal
    build: ./api-gateway-internal
    ports:
      - "8080:8080"  # Internal gateway
    networks:
      - soa-net

  # === Prosumers ===
  trip-planner:
    image: trip-planner
    build: ./tripPlanner/
    ports:
      - "8090:8090"
    depends_on:
      - api-gateway-internal
    networks:
      - soa-net

  location-availability:
    image: location-availability
    build: ./locationAvailability/
    depends_on:
      - api-gateway-internal
    networks:
      - soa-net

  # === Providers ===
  provider-trails:
    image: provider-trails
    build: ./provider-trails
    ports:
      - "8081:8081"
    networks:
      - soa-net

  provider-weather:
    image: provider-weather
    build: ./provider-weather
    ports:
      - "8082:8082"
    networks:
      - soa-net

  provider-events:
    image: provider-events
    build: ./provider-events
    ports:
      - "8084:8084"
    networks:
      - soa-net
  
  # # Optional provider for local gastronomy
  # provider-food:
  #   image: provider-food
  #   build: ./provider-food
  #   networks:
  #     - soa-net

  provider-food:
    image: provider-food
    build: ./provider-food
    ports:
      - "8083:8083"
    networks:
      - soa-net
    environment:
      SPRING_PROFILES_ACTIVE: default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/food-api/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  soa-net:
    driver: bridge
