server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: provider-trails
              uri: http://provider-trails:8081
              predicates:
                - Path=/trails-api/**

            - id: weather-provider
              uri: http://localhost:8082
              predicates:
                - Path=/weather-api/**

            - id: events-service
              uri: http://provider-events:8083
              predicates:
                - Path=/events-api/**

            - id: food-service
              uri: http://provider-food:8084
              predicates:
                - Path=/food-api/**

            - id: itinerary-aggregator
              uri: http://itinerary-aggregator:8082
              predicates:
                - Path=/itinerary-api/**

            - id: availability-coordinator
              uri: http://availability-coordinator:8081
              predicates:
                - Path=/availability-api/**

