server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: provider-trails
              uri: http://provider-trails:8081
              predicates:
                - Path=/trails-api/**

            - id: weather-provider
              uri: http://localhost:8082
              predicates:
                - Path=/weather-api/**

            - id: events-service
              uri: http://provider-events:8084
              predicates:
                - Path=/events-api/**

            - id: food-service
              uri: http://provider-food:8083
              predicates:
                - Path=/food-api/**

            - id: locationAvailability
              uri: http://locationAvailability
              predicates:
                - Path=/itinerary-api/**

            - id: tripPlanner
              uri: http://tripPlanner
              predicates:
                - Path=/availability-api/**

