server:
  server:
  port: 8091
  address: 0.0.0.0  # Aggiungi questa linea
  servlet:
    context-path: /location-availability

spring:
  application:
    name: location-availability-service
  main:
    web-application-type: servlet  # Forza il tipo di applicazione
  datasource:
    url: jdbc:h2:mem:availabilitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
