
package com.example.weather.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LocationNotFoundException", targetNamespace = "http://services.provider_weather.spring.rest/")
public class LocationNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LocationNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LocationNotFoundException_Exception(String message, LocationNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LocationNotFoundException_Exception(String message, LocationNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.weather.client.LocationNotFoundException
     */
    public LocationNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
